# Generated by Django 3.1.1 on 2020-09-17 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_rented', models.DateTimeField(default=None)),
                ('last_sickbay', models.DateTimeField(default=None)),
                ('last_service', models.TextField()),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('fixture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.fixture')),
            ],
            bases=('inventory.fixture',),
        ),
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('fixture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.fixture')),
            ],
            bases=('inventory.fixture',),
        ),
    ]
