# Generated by Django 3.1.1 on 2020-09-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='source',
            field=models.CharField(choices=[('led', 'LED'), ('conventional', 'Conventional'), ('mover', 'Mover')], default='conventional', max_length=20),
        ),
    ]
