# Generated by Django 3.1.1 on 2020-09-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200918_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
