# Generated by Django 3.1.1 on 2020-09-20 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200918_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Kind',
            new_name='Source_Type',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='kind',
            new_name='source_type',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='model',
        ),
        migrations.CreateModel(
            name='Fixture_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='fixture_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.fixture_type'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.manufacturer'),
        ),
    ]
